dist: trusty
sudo: false

language: go

go:
  - 1.9

env:
  - GOMAXPROCS=4 DEP_VERSION=0.4.1

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - ./build.sh
  - ./test/tests.sh

after_success:
  - cd test && bash <(curl -s https://codecov.io/bash) -t 7a1058c2-aeb2-484b-bcb0-7fae48633926
